language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
install:
  - pip install coveralls six
  - pip install --upgrade mock
script:
  - coverage run -m unittest discover -s tests
after_success:
  - coveralls